#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Make paper tables/figures from existing evaluation results.

Input:
- tools/research/models_dgcf_simple.json
- each model work_dir/evaluation generated by evaluate_benchmark.py

Output:
paper_outputs_dgcf_simple/
- tables/*.csv
- figures/*.png and *.pdf

Nếu parser không bắt đúng file JSON/CSV evaluator của bạn, mở file evaluation ra xem tên metric,
rồi thêm alias vào METRIC_KEYS phía dưới.
"""

import argparse
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


CORRUPTIONS = ["brightness", "contrast", "gaussian_noise", "defocus_blur", "motion_blur"]
DISPLAY = {
    "brightness": "Brightness",
    "contrast": "Contrast",
    "gaussian_noise": "Gaussian Noise",
    "defocus_blur": "Defocus Blur",
    "motion_blur": "Motion Blur",
    "clean": "Clean",
}
METRIC_KEYS = {
    "segm_mAP": ["coco/segm_mAP", "segm_mAP", "mask_mAP", "mask_AP", "mean_mask_ap"],
    "bbox_mAP": ["coco/bbox_mAP", "bbox_mAP", "box_mAP", "box_AP"],
    "segm_mAP_50": ["coco/segm_mAP_50", "segm_mAP_50", "mask_AP50"],
    "segm_mAP_75": ["coco/segm_mAP_75", "segm_mAP_75", "mask_AP75"],
    "bbox_mAP_50": ["coco/bbox_mAP_50", "bbox_mAP_50", "bbox_AP50"],
    "bbox_mAP_75": ["coco/bbox_mAP_75", "bbox_mAP_75", "bbox_AP75"],
}


def load_models(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))["models"]


def find_metric(row, aliases):
    for k in aliases:
        if k in row:
            try:
                return float(row[k])
            except Exception:
                return np.nan
    return np.nan


def flatten(obj):
    out = []
    if isinstance(obj, dict):
        if any(k in obj for keys in METRIC_KEYS.values() for k in keys):
            out.append(obj)
        for v in obj.values():
            out.extend(flatten(v))
    elif isinstance(obj, list):
        for v in obj:
            out.extend(flatten(v))
    return out


def infer_condition(path, row=None):
    row = row or {}
    corr = row.get("corruption", row.get("condition", row.get("corruption_type", "")))
    sev = row.get("severity", row.get("level", row.get("sev", None)))
    text = str(path).lower()

    if not corr:
        if "clean" in text:
            corr = "clean"
        else:
            for c in CORRUPTIONS:
                if c in text:
                    corr = c
                    break

    if isinstance(corr, str):
        corr = corr.lower().replace(" ", "_").replace("-", "_")
        m = re.match(r"(.+?)[_\-]?s([1-5])$", corr)
        if m:
            corr = m.group(1)
            sev = int(m.group(2))

    if sev is None or str(sev).lower() in ["", "none", "nan"]:
        m = re.search(r"(?:severity|sev|s)[_\-]?([1-5])", text)
        if m:
            sev = int(m.group(1))
        else:
            sev = 0 if corr == "clean" else np.nan

    try:
        sev = int(sev)
    except Exception:
        sev = 0

    return corr, sev


def parse_json(path, model_name):
    rows = []
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return rows
    for r in flatten(obj):
        metrics = {mk: find_metric(r, aliases) for mk, aliases in METRIC_KEYS.items()}
        if all(pd.isna(v) for v in metrics.values()):
            continue
        corr, sev = infer_condition(path, r)
        rows.append({"model": model_name, "corruption": corr, "severity": sev, "source": str(path), **metrics})
    return rows


def parse_csv(path, model_name):
    rows = []
    try:
        df = pd.read_csv(path)
    except Exception:
        return rows
    for _, s in df.iterrows():
        r = s.to_dict()
        metrics = {mk: find_metric(r, aliases) for mk, aliases in METRIC_KEYS.items()}
        if all(pd.isna(v) for v in metrics.values()):
            continue
        corr, sev = infer_condition(path, r)
        rows.append({"model": model_name, "corruption": corr, "severity": sev, "source": str(path), **metrics})
    return rows


def collect(models):
    rows = []
    for m in models:
        eval_dir = Path(m["work_dir"]) / "evaluation"
        if not eval_dir.exists():
            print(f"[WARN] no eval dir: {m['name']} -> {eval_dir}")
            continue
        files = list(eval_dir.rglob("*.json")) + list(eval_dir.rglob("*.csv"))
        print(f"[COLLECT] {m['name']}: {len(files)} files")
        for f in files:
            if f.suffix == ".json":
                rows += parse_json(f, m["name"])
            elif f.suffix == ".csv":
                rows += parse_csv(f, m["name"])
    df = pd.DataFrame(rows)
    if df.empty:
        raise RuntimeError("No metrics found. Check evaluate_benchmark.py outputs.")
    return df


def save_heatmap(piv, path, title, label):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = piv.values.astype(float)
    plt.figure(figsize=(max(8, 1.25 * len(piv.columns) + 2), max(4.5, 0.5 * len(piv.index) + 1.5)))
    im = plt.imshow(data, aspect="auto")
    plt.colorbar(im, label=label)
    plt.title(title)
    plt.xticks(range(len(piv.columns)), piv.columns, rotation=35, ha="right")
    plt.yticks(range(len(piv.index)), piv.index)
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if np.isfinite(data[i, j]):
                plt.text(j, i, f"{data[i, j]:.3f}", ha="center", va="center", fontsize=8)
    plt.tight_layout()
    plt.savefig(path.with_suffix(".png"), dpi=300)
    plt.savefig(path.with_suffix(".pdf"))
    plt.close()


def order_rows(piv, models):
    order = [m["name"] for m in models]
    keep = [x for x in order if x in piv.index]
    rest = [x for x in piv.index if x not in keep]
    return piv.loc[keep + rest]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--models", default="tools/research/models_dgcf_simple.json")
    p.add_argument("--out-dir", default="paper_outputs_dgcf_simple")
    args = p.parse_args()

    models = load_models(args.models)
    out = Path(args.out_dir)
    tables = out / "tables"
    figs = out / "figures"
    tables.mkdir(parents=True, exist_ok=True)
    figs.mkdir(parents=True, exist_ok=True)

    raw = collect(models)
    raw.to_csv(tables / "raw_metrics.csv", index=False)

    metric_cols = list(METRIC_KEYS.keys())
    df = raw.groupby(["model", "corruption", "severity"], dropna=False)[metric_cols].mean(numeric_only=True).reset_index()
    df.to_csv(tables / "metrics_by_condition.csv", index=False)

    clean = df[df["corruption"].eq("clean")]
    clean_table = clean.groupby("model")[metric_cols].mean(numeric_only=True)
    clean_table = order_rows(clean_table, models)
    clean_table.to_csv(tables / "clean_performance.csv")

    corr = df[df["corruption"].isin(CORRUPTIONS)]
    by_corr = corr.groupby(["model", "corruption"])["segm_mAP"].mean().reset_index()
    piv_corr = by_corr.pivot_table(index="model", columns="corruption", values="segm_mAP")
    piv_corr = order_rows(piv_corr.reindex(columns=CORRUPTIONS), models)
    piv_corr_display = piv_corr.copy()
    piv_corr_display.columns = [DISPLAY.get(c, c) for c in piv_corr_display.columns]
    piv_corr_display["Mean"] = piv_corr_display.mean(axis=1)
    piv_corr_display.to_csv(tables / "mean_mask_ap_by_corruption.csv")
    save_heatmap(piv_corr_display.drop(columns=["Mean"]), figs / "mean_mask_ap_by_corruption",
                 "Mean Mask AP over Severity 1–5 for Selected Corruptions", "Mean mask AP")

    sev = corr.groupby(["model", "severity"])["segm_mAP"].mean().reset_index()
    piv_sev = sev.pivot_table(index="model", columns="severity", values="segm_mAP")
    piv_sev = order_rows(piv_sev, models)
    piv_sev.columns = [f"S{int(c)}" for c in piv_sev.columns]
    piv_sev.to_csv(tables / "mean_mask_ap_by_severity.csv")
    save_heatmap(piv_sev, figs / "mean_mask_ap_by_severity",
                 "Mean Mask AP by Severity over Selected Corruptions", "Mean mask AP")

    clean_ap = clean.groupby("model")["segm_mAP"].mean()
    mean_corr = by_corr.groupby("model")["segm_mAP"].mean()
    worst = by_corr.groupby("model")["segm_mAP"].min()
    s5 = corr[corr["severity"].eq(5)].groupby("model")["segm_mAP"].mean()

    summary = pd.DataFrame({
        "clean_mask_ap": clean_ap,
        "mean_corrupted_mask_ap": mean_corr,
        "RD": clean_ap - mean_corr,
        "SI": mean_corr / clean_ap,
        "worst_corruption_ap": worst,
        "severity5_ap": s5,
    })
    summary = order_rows(summary, models)
    summary.to_csv(tables / "robustness_summary.csv")

    # RD and SI heatmaps by corruption.
    rd = piv_corr.copy()
    si = piv_corr.copy()
    for m in rd.index:
        rd.loc[m] = clean_ap.get(m, np.nan) - piv_corr.loc[m]
        si.loc[m] = piv_corr.loc[m] / clean_ap.get(m, np.nan)
    rd.columns = [DISPLAY.get(c, c) for c in rd.columns]
    si.columns = [DISPLAY.get(c, c) for c in si.columns]
    rd.to_csv(tables / "rd_by_corruption.csv")
    si.to_csv(tables / "si_by_corruption.csv")
    save_heatmap(rd, figs / "rd_by_corruption", "Robustness Drop by Corruption", "RD")
    save_heatmap(si, figs / "si_by_corruption", "Stability Index by Corruption", "SI")

    # Severity line.
    plt.figure(figsize=(8, 5))
    for model, g in sev.groupby("model"):
        g = g.sort_values("severity")
        plt.plot(g["severity"], g["segm_mAP"], marker="o", label=model)
    plt.xlabel("Severity")
    plt.ylabel("Mean mask AP")
    plt.title("Severity-wise Mean Mask AP")
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(figs / "severity_curves.png", dpi=300)
    plt.savefig(figs / "severity_curves.pdf")
    plt.close()

    report = "# DGCF simple experiment summary\n\n"
    report += summary.to_markdown(floatfmt=".3f")
    report += "\n\nMain claim: compare Enhanced Mask R-CNN (DGCF) directly with Mask R-CNN R50.\n"
    (out / "summary_report.md").write_text(report, encoding="utf-8")

    print(f"[DONE] {out}")


if __name__ == "__main__":
    main()
